# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
    - dev
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        if [ -f api_yamdb/requirements.txt ]; then pip install -r api_yamdb/requirements.txt; fi
    - name: Lint with flake8
      run: |
        python3 -m flake8
    - name: Test with pytest
      run: |
        pytest
    - name: Build and upload docker image
      run: |
        cd api_yamdb
        echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        docker build . -t hrapovd/api_yamdb:1.0
        docker push hrapovd/api_yamdb:1.0
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -x
          if [ -d yamdb_final ]; then
            cd yamdb_final/infra
            sudo docker-compose down
            sudo docker rmi hrapovd/api_yamdb:1.0
            sudo docker system prune -f
            sudo docker volume rm infra_static_value
            cd ~
            rm -rf ~/yamdb_final
          fi
          git clone git@github.com:hrapovd1/yamdb_final.git
          cd yamdb_final
          git checkout dev
          cd infra
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASS }} >> .env
          sudo docker-compose up -d
          sudo echo "#-------{ Setup app }-------------"
          sudo docker-compose exec web python3 manage.py migrate
          sudo docker-compose exec web python3 manage.py collectstatic --noinput
          sudo docker-compose exec web python3 manage.py importcsv
    - name: Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен! 

